.deploy:
    before_script: 
        - export IFS='/'
        - read -ra TAG <<< "$CI_COMMIT_TAG"
        - LEN=${#TAG[@]}
        - export PROJECT_VERSION=$(echo ${TAG[3]})
        - unset IFS

    script:
        - cp -r ${CONFIG_PATH}application.conf ${DEPLOY_PATH}application.conf
        - cp -r ${CONFIG_PATH}routes ${DEPLOY_PATH}routes
        - cd ${DEPLOY_PATH}
        - /twk8s/helm3 upgrade --install --namespace ds02 --kubeconfig ${K8S_CONFIG_PATH} --set image.tag=${PROJECT_VERSION} data-factory -f values/data-factory.yaml .

    tags:
        - public
    only:
        - /^release\/ola\/wro\/.*$/
    

deploy-tw-prod:
    stage: deploy-prod
    extends: .deploy
    variables:
        K8S_CONFIG_PATH: /twk8s/prod/config
        CONFIG_PATH: conf/tw/prod/
        DEPLOY_PATH: deploy/deployment/
    script:
        - cp -r ${CONFIG_PATH}application.conf ${DEPLOY_PATH}configMapGenerator/application.conf
        - cp -r ${CONFIG_PATH}routes ${DEPLOY_PATH}configMapGenerator/routes
        - kubectl apply -k ${DEPLOY_PATH}configMapGenerator/ --namespace=${NAMESPACE} --kubeconfig ${K8S_CONFIG_PATH} 
        - kubectl apply -f ${DEPLOY_PATH}Deployment.yaml --namespace=${NAMESPACE} --kubeconfig ${K8S_CONFIG_PATH}
        - kubectl set image deployment/${PROJECT_NAME} ${PROJECT_NAME}=${REGISTRY_PATH}:${PROJECT_VERSION} --kubeconfig ${K8S_CONFIG_PATH} --namespace=${NAMESPACE}
    only:
        - /^release\/tw\/prod\/.*$/

signimage-olathe:
    stage: signimage
    extends: .deploy
    script:
      - echo "pass"

    only:
      - /^release\/tw\/prod\/.*$/

    tags:
      - public

olawroTag:
    stage: tagOLAWRO
    extends: .deploy
    variables:
        ENV: "ola/wro"
    script:
        - git branch -a
        - git remote set-url origin ${PROJECT_URL}
        - TAG=release/${ENV}/${PROJECT_VERSION}
        - git tag -a ${TAG} -m "Version created by gitlab-ci Build"
        - git push origin ${TAG}

    only:
        - /^release\/tw\/prod\/.*$/
    when: manual

deploy-ola:stag:
    stage: deploy-ola-stag
    extends: .deploy
    variables:
        K8S_CONFIG_PATH: /olathek8s/stage/config
        CONFIG_PATH: conf/ola/stag/
        DEPLOY_PATH: deploy/olaChart/stag/

deploy-ola:prod:
    stage: deploy-ola-prod
    extends: .deploy
    variables:
        K8S_CONFIG_PATH: /olathek8s/prod/config
        CONFIG_PATH: conf/ola/prod/
        DEPLOY_PATH: deploy/olaChart/prod/

deploy-wro-prod:
    stage: deploy-wro-prod
    extends: .deploy
    variables:
        K8S_CONFIG_PATH: /polandk8s/prod/config
        CONFIG_PATH: conf/wro/prod/
        DEPLOY_PATH: deploy/wroChart/prod/
